version: "3.9"

services:
  f1-telemetry:
    build: .
    restart: unless-stopped
    ports:
      - "30001-30010:30001-30010"
      - "20001-20010:20001-20010/udp"
    volumes:
      - ./recorder/sessions:/app/recorder/sessions
    env_file:
      - .env
